### ISSUE TITLE
JSON schema file name and location should not be hard-coded

### ISSUE THREAD

**Issue by glarrain-cdd** [ForestAdmin/django-forestadmin#135]
## Expected behavior

The file `.forestadmin-schema.json` is very important and, it will trigger an error in production will be triggered.

At least, it should be defined as a constant and properly documented. Related to this issue is the undocumented behavior of how and when it is generated (it depends on the value of `settings.DEBUG`).

Bonus: customizable name and location through Django settings.

## Actual behavior

The filename is hard-coded in two methods of `django_forest.utils.schema.Schema`

- handle_schema_file_production
- handle_schema_file

https://github.com/ForestAdmin/django-forestadmin/blob/37b8cb575f99142722b8d7f22d83c7b38a5dafc1/django_forest/utils/schema/__init__.py#L135-L158

TODO: Please provide any relevant information about your setup.

* Package Version: 1.5.0
* Django Version: irrelevant

**Comment by jbarreau** [comment]
Hello @glarrain-cdd,
Yes, the .forestadmin-schema.json is hardcoded, but the interest of this file is mostly for forestadmin, and I don't understand why as user of django-forestadmin you could be interested in this file. 
Can you tell me what is your need about this file location.

Best regards.

**Comment by glarrain-cdd** [comment]
Thanks for your comments.

Considerations and questions:

- running in production (DEBUG=False) the agent expects that this file exists. If it does not, it will crash.

- it is common good practice for running production web apps using Docker (or even without it) that the OS user used for running the web server is not allowed to write to the filesystem.

- for production, was it the idea that the file was generated on web start, or that it already existed?

  - if generated, it will happen for each web worker each time it starts (perhaps not too terrible)

  - if it had to exist, should it be versioned in the codebase or generated in some build stage (for example, like when `collectstatic` is executed)?

**Comment by jbarreau** [comment]
Hi, 
To explain this file lifecycle and how it is used by forest : 

1. In development : It is created at the project launch and send to the forest server (we send an hash in a first time, to not flood the server), and this operation repeat multiple time in dev
2. This file is committed in your CVS
3. In production : the agent re-use the committed file, and send it to the server (if the hash has changed since the last time it was sent).

To explicitly answer your questions : 

- The file is mandatory in production because we want to force users to have a development environment before to deploy in production, and this workflow is the same in the front-end of forestadmin. 
For more informations about the development workflow you can take a look at theses docs : https://docs.forestadmin.com/documentation/getting-started/setup-guide and https://docs.forestadmin.com/documentation/getting-started/development-workflow
- No need to have write permission in production for this file
- In production this file **have to** exists, it **will not** be regenerated, so it should be versioned with your codebase.

Hoping theses informations help you.
Don't hesitate to visit our community forum : https://community.forestadmin.com

Best regards.

**Comment by arnaudbesnier** [comment]
> running in production (DEBUG=False) the agent expects that this file exists. If it does not, it will crash.

Sounds like a bug to me, the agent should not crash the server instance on start if the `.forestadmin-schema.json` is missing/not versioned.

**Comment by jbarreau** [comment]
https://github.com/ForestAdmin/django-forestadmin/pull/139
